#!/usr/bin/env python3
"""Flowsight enrollment: identify a device when it asks for an address, then
place it in the zone that matches what it is.

The problem this solves is that a flat network gives a smart plug the same
reach as a laptop. Enrollment watches DHCP, fingerprints each device from the
signals the request itself carries, and assigns it an address inside a zone
whose subnet, DNS and firewall policy suit that class of device. Anything it
cannot identify goes to the captive zone, where HTTP is answered by an
identification page instead of the internet.

Two deliberate safety properties:

  * "monitor" mode classifies and reports but writes no enforcement. It is the
    default, because the cost of a wrong rule here is a device that silently
    loses the network.
  * Devices already on the network when enrollment is first enabled are pinned
    where they are. Only devices first seen after that are placed. Migrating an
    existing device is an explicit action, never a side effect of adding a rule.
"""

import argparse
import ipaddress
import json
import os
import re
import subprocess
import sys
import time
import urllib.request

CONF_DIR = os.environ.get("FLOWSIGHT_ETC", "/usr/local/etc/flowsight")
STATE_DIR = os.environ.get("FLOWSIGHT_STATE", "/var/db/flowsight")
ZONES_FILE = os.path.join(CONF_DIR, "zones.json")
RULES_FILE = os.path.join(CONF_DIR, "enroll-rules.json")
REGISTRY = os.path.join(STATE_DIR, "enroll-registry.json")
SPOOL = os.path.join(STATE_DIR, "enroll-events.jsonl")
LEASES = "/var/db/dnsmasq.leases"
DNSMASQ_DROPIN = "/usr/local/etc/dnsmasq.conf.d/flowsight-zones.conf"
PF_ANCHOR = "/usr/local/etc/flowsight/pf-enroll.conf"
HOSTMAP_URL = "http://192.168.1.252:9099/hostmap.json"
NTOPNG = "http://127.0.0.1:3000"

GENERATED = "# Generated by flowsight-enroll. Edits are overwritten on apply.\n"
MAC_RE = re.compile(r"^[0-9A-F]{2}(:[0-9A-F]{2}){5}$")


# --------------------------------------------------------------------------
# storage


def _read_json(path, default):
    try:
        with open(path) as fh:
            return json.load(fh)
    except Exception:
        return default


def _write_json(path, data):
    """Write whole-file or not at all.

    The registry is the record of which device belongs where; a half-written
    one would silently re-quarantine devices that were already identified.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)
    tmp = path + ".tmp"
    with open(tmp, "w") as fh:
        json.dump(data, fh, indent=1, sort_keys=True)
    os.replace(tmp, path)


def load_zones():
    return _read_json(ZONES_FILE, {"mode": "monitor", "zones": []})


def load_rules():
    return _read_json(RULES_FILE, {"rules": []}).get("rules", [])


def load_registry():
    return _read_json(REGISTRY, {"devices": {}, "enabled_at": 0})


def save_registry(reg):
    _write_json(REGISTRY, reg)


# --------------------------------------------------------------------------
# signals


def is_pseudo_mac(mac):
    """Broadcast and multicast addresses, which are destinations, not devices."""
    if not mac or mac == "FF:FF:FF:FF:FF:FF":
        return True
    if mac.startswith(("01:00:5E", "33:33")):
        return True
    try:
        return bool(int(mac.split(":")[0], 16) & 1)
    except ValueError:
        return True


def is_randomized_mac(mac):
    """True for a locally administered address.

    Current iOS, Android and Windows rotate a private MAC per network by
    default, so the OUI identifies nothing. Classification for these has to
    lean on the hostname and DHCP fingerprint instead, and this flag is what
    tells the rules - and the person reading the UI - that the vendor column is
    empty by design rather than by failure.
    """
    try:
        return bool(int(mac.split(":")[0], 16) & 2)
    except (ValueError, IndexError):
        return False


def leases():
    """MAC -> {ip, hostname} from the dnsmasq lease file."""
    out = {}
    try:
        with open(LEASES) as fh:
            for line in fh:
                p = line.split()
                if len(p) < 4:
                    continue
                name = p[3] if p[3] != "*" else ""
                mac, addr = p[1].upper(), p[2]
                if not MAC_RE.match(mac):
                    # DHCPv6 lease lines carry an IAID in this column and the
                    # DUID at the end - there is no MAC in them at all. Parsing
                    # them as MACs invented devices named after integers.
                    continue
                rec = out.setdefault(mac, {"ip": "", "ip6": "", "hostname": "",
                                           "expires": 0})
                # A device with both a v4 lease and a DHCPv6/SLAAC entry has two
                # lines here. Keying by MAC alone let the v6 line overwrite the
                # v4 address, which is the one every other view is keyed on.
                if ":" in addr:
                    rec["ip6"] = addr
                else:
                    rec["ip"] = addr
                rec["hostname"] = rec["hostname"] or name
                rec["expires"] = max(rec["expires"], int(p[0]))
    except Exception:
        pass
    return out


def hostmap():
    try:
        with urllib.request.urlopen(HOSTMAP_URL, timeout=10) as r:
            return json.loads(r.read().decode())
    except Exception:
        return {}


def ntopng_macs():
    """MAC -> {manufacturer, device_type} from ntopng's OUI and traffic view."""
    url = ("%s/lua/rest/v2/get/mac/macs_list.lua?ifid=0&perPage=250" % NTOPNG)
    try:
        with urllib.request.urlopen(url, timeout=20) as r:
            rsp = json.loads(r.read().decode()).get("rsp", {})
        rows = rsp.get("data", rsp) if isinstance(rsp, dict) else rsp
        out = {}
        for m in rows or []:
            out[(m.get("mac") or "").upper()] = {
                "manufacturer": m.get("manufacturer") or "",
                "device_type": (m.get("device_type") or {}).get(
                    "device_type_label", ""),
            }
        return out
    except Exception:
        return {}


def drain_spool():
    """Consume DHCP events written by the dnsmasq hook.

    The hook runs inside dnsmasq's request path, so it only appends a line and
    exits; all interpretation happens here. The file is renamed before reading
    so a request arriving mid-drain is not lost.
    """
    events = []
    if not os.path.exists(SPOOL):
        return events
    taken = SPOOL + ".taken"
    try:
        os.replace(SPOOL, taken)
        with open(taken) as fh:
            for line in fh:
                line = line.strip()
                if line:
                    try:
                        events.append(json.loads(line))
                    except ValueError:
                        continue
        os.unlink(taken)
    except Exception:
        pass
    return events


def gather():
    """Everything known about every MAC, merged into one signal dict."""
    lz, hm, nt = leases(), hostmap(), ntopng_macs()
    macs = set(lz) | set(hm) | set(nt)
    sig = {}
    for mac in macs:
        if is_pseudo_mac(mac):
            # Broadcast and multicast destinations are not devices and can
            # never ask for an address; enrolling them would fill the
            # quarantine list with things that cannot be identified.
            continue
        g = hm.get(mac) or {}
        l = lz.get(mac) or {}
        n = nt.get(mac) or {}
        sig[mac] = {
            "mac": mac,
            "ip": l.get("ip", ""),
            "hostname": l.get("hostname", "") or g.get("name", ""),
            "vendor": n.get("manufacturer", ""),
            "device_type": n.get("device_type", ""),
            "guest_kind": g.get("kind", ""),
            "guest_name": g.get("name", ""),
            "vendor_class": "",
            "fingerprint": "",
            "ip6": l.get("ip6", ""),
            "randomized_mac": is_randomized_mac(mac),
        }
    return sig


# --------------------------------------------------------------------------
# classification


def _match_cond(cond, s):
    """One condition block. Every key must match; a list inside a key is an OR."""
    for key, want in cond.items():
        if key == "any":
            if not any(_match_cond(c, s) for c in want):
                return False
        elif key == "vendor":
            v = (s.get("vendor") or "").lower()
            if not v or not any(w.lower() in v for w in want):
                return False
        elif key == "guest_kind":
            if (s.get("guest_kind") or "") not in want:
                return False
        elif key.endswith("_re"):
            field = key[:-3]
            if not re.search(want, s.get(field) or ""):
                return False
        elif key == "mac_prefix":
            if not any((s.get("mac") or "").startswith(w.upper()) for w in want):
                return False
        else:
            if (s.get(key) or "") != want:
                return False
    return True


def classify(sig, rules):
    """First matching rule wins. Returns (zone_id, rule_id, confidence, why)."""
    for rule in rules:
        try:
            if _match_cond(rule.get("when", {}), sig):
                return (rule.get("zone", ""), rule.get("id", ""),
                        rule.get("confidence", "medium"), rule.get("why", ""))
        except re.error:
            continue
    return ("", "", "none", "No rule matched this device.")


# --------------------------------------------------------------------------
# reconcile


def reconcile(zones=None, rules=None):
    """Fold current signals and queued DHCP events into the registry.

    Returns the registry. Never changes a zone a human set, and never moves a
    device that predates enrollment.
    """
    zones = zones or load_zones()
    rules = rules if rules is not None else load_rules()
    reg = load_registry()
    devices = reg.setdefault("devices", {})
    captive = zones.get("captive_zone", "quarantine")
    first_run = not reg.get("enabled_at")
    if first_run:
        reg["enabled_at"] = int(time.time())

    sig = gather()
    # DHCP events carry the two signals nothing else can see.
    for ev in drain_spool():
        mac = (ev.get("mac") or "").upper()
        if not MAC_RE.match(mac):
            # A DHCPv6 event with no known hardware address carries only a DUID.
            # It names a client we cannot join to the layer-2 inventory, so
            # there is nothing to enrol.
            continue
        s = sig.setdefault(mac, {"mac": mac})
        for k in ("vendor_class", "fingerprint", "hostname", "ip"):
            if ev.get(k):
                s[k] = ev[k]
        d = devices.setdefault(mac, {})
        d["last_dhcp"] = ev.get("at", int(time.time()))
        d["last_action"] = ev.get("action", "")

    now = int(time.time())
    for mac, s in sig.items():
        d = devices.setdefault(mac, {})
        seen_before = bool(d.get("first_seen"))
        d.setdefault("first_seen", now)
        d["last_seen"] = now
        d["mac"] = mac
        d["randomized_mac"] = s.get("randomized_mac", False)
        for k in ("ip", "ip6", "hostname", "vendor", "device_type", "guest_kind",
                  "guest_name"):
            if s.get(k):
                d[k] = s[k]
        for k in ("vendor_class", "fingerprint"):
            if s.get(k):
                d[k] = s[k]

        zone, rule_id, conf, why = classify({**s, **d}, rules)
        d["suggested_zone"] = zone or captive
        d["rule"] = rule_id
        d["confidence"] = conf
        d["why"] = why

        if d.get("zone_source") == "manual":
            continue
        if first_run and not seen_before:
            # Everything present the moment enrollment is switched on keeps the
            # address it already has. Placing them would renumber a working
            # network in one step.
            d["zone"] = "__existing__"
            d["zone_source"] = "pinned"
            d["state"] = "pinned"
            continue
        d["zone"] = zone or captive
        d["zone_source"] = "rule" if zone else "default"
        d["state"] = "classified" if zone else "unidentified"

    reg["updated_at"] = now
    save_registry(reg)
    return reg


def assign(mac, zone_id, source="manual"):
    reg = load_registry()
    d = reg.setdefault("devices", {}).setdefault(mac.upper(), {})
    d["zone"] = zone_id
    d["zone_source"] = source
    d["state"] = "classified"
    d["assigned_at"] = int(time.time())
    save_registry(reg)
    return d


# --------------------------------------------------------------------------
# rendering


def _hosts_for_zone(reg, zone_id):
    out = []
    for mac, d in sorted(reg.get("devices", {}).items()):
        if d.get("zone") == zone_id:
            out.append((mac, d))
    return out


def render_dnsmasq(zones, reg):
    """dnsmasq drop-in: a tagged range per zone, and a tag per known device.

    Placement is by tag rather than by fixed address: dnsmasq picks an address
    from the range carrying the device's tag, so a device moves zone simply by
    changing its tag, with no address bookkeeping here.
    """
    lease = zones.get("lease", "2h")
    lines = [GENERATED, "\n"]
    for z in zones.get("zones", []):
        zid = z["id"]
        net = ipaddress.ip_network(z["subnet"], strict=False)
        lines.append("# zone: %s - %s\n" % (zid, z.get("name", "")))
        lines.append("dhcp-range=set:%s,%s,%s,%s,%s\n" % (
            zid, z["range"][0], z["range"][1], net.netmask, lease))
        if z.get("gateway"):
            lines.append("dhcp-option=tag:%s,option:router,%s\n" % (zid, z["gateway"]))
        for dns in z.get("dns", []):
            lines.append("dhcp-option=tag:%s,option:dns-server,%s\n" % (zid, dns))
        lines.append("\n")

    lines.append("# device placements\n")
    for mac, d in sorted(reg.get("devices", {}).items()):
        zid = d.get("zone", "")
        if not zid or zid == "__existing__":
            continue
        name = re.sub(r"[^A-Za-z0-9-]", "", (d.get("hostname") or "").replace(" ", "-"))
        tail = ",%s" % name if name else ""
        lines.append("dhcp-host=%s,set:%s%s\n" % (mac.lower(), zid, tail))
    return "".join(lines)


def render_pf(zones, reg):
    """pf rules for zone isolation and the captive redirect.

    Written as a standalone file loaded into an anchor so that nothing here can
    disturb the rules OPNsense generates from its own configuration.
    """
    lines = [GENERATED, "\n"]
    by_id = {z["id"]: z for z in zones.get("zones", [])}
    for z in zones.get("zones", []):
        lines.append("table <fs_%s> persist { %s }\n" % (z["id"], z["subnet"]))
    lines.append("\n")

    for z in zones.get("zones", []):
        zid = z["id"]
        if z.get("captive"):
            # The identification page answers port 80 for anything in the zone.
            # Captive-portal detection on every major OS probes HTTP, so this
            # is what makes the sign-in sheet appear on its own.
            lines.append(
                "rdr on $lan proto tcp from <fs_%s> to any port 80 -> %s port 8080\n"
                % (zid, z.get("gateway", "")))
            lines.append("block drop quick from <fs_%s> to any\n" % zid)
            lines.append("pass quick from <fs_%s> to %s\n" % (zid, z.get("gateway", "")))
            continue
        allowed = z.get("reach_zones", [])
        for other in by_id:
            if other == zid or other in allowed:
                continue
            lines.append("block drop quick from <fs_%s> to <fs_%s>\n" % (zid, other))
        if not z.get("internet", True):
            lines.append("block drop quick from <fs_%s> to !<fs_%s>\n" % (zid, zid))
    return "".join(lines)


# --------------------------------------------------------------------------
# CLI


def cmd_status(args):
    zones, reg = load_zones(), load_registry()
    devices = reg.get("devices", {})
    counts = {}
    for d in devices.values():
        counts[d.get("zone", "?")] = counts.get(d.get("zone", "?"), 0) + 1
    print("mode:      %s" % zones.get("mode", "monitor"))
    print("zones:     %s" % ", ".join(z["id"] for z in zones.get("zones", [])))
    print("rules:     %d" % len(load_rules()))
    print("devices:   %d" % len(devices))
    for zid, n in sorted(counts.items(), key=lambda kv: -kv[1]):
        print("  %-14s %d" % (zid, n))
    pending = [d for d in devices.values() if d.get("state") == "unidentified"]
    print("unidentified: %d" % len(pending))
    return 0


def cmd_devices(args):
    reg = reconcile() if args.refresh else load_registry()
    rows = sorted(reg.get("devices", {}).values(),
                  key=lambda d: (d.get("zone", ""), d.get("hostname", "")))
    print("%-18s %-16s %-15s %-11s %-11s %-8s %s" %
          ("MAC", "HOSTNAME", "IP", "ZONE", "SUGGESTED", "CONF", "VENDOR"))
    for d in rows:
        if args.zone and d.get("zone") != args.zone:
            continue
        print("%-18s %-16s %-15s %-11s %-11s %-8s %s" % (
            d.get("mac", ""), (d.get("hostname") or "")[:16], d.get("ip", ""),
            d.get("zone", ""), d.get("suggested_zone", ""),
            d.get("confidence", ""), (d.get("vendor") or "")[:26]))
    return 0


def cmd_plan(args):
    zones, rules = load_zones(), load_rules()
    reg = reconcile(zones, rules)
    print("=== %s ===" % DNSMASQ_DROPIN)
    print(render_dnsmasq(zones, reg))
    print("=== %s ===" % PF_ANCHOR)
    print(render_pf(zones, reg))
    if zones.get("mode") != "enforce":
        print("mode is %r - apply would write nothing." % zones.get("mode"))
    return 0


def cmd_apply(args):
    zones, rules = load_zones(), load_rules()
    if zones.get("mode") != "enforce" and not args.force:
        print("mode is %r; refusing to write. Set mode to \"enforce\" in %s, "
              "or pass --force." % (zones.get("mode"), ZONES_FILE))
        return 1
    reg = reconcile(zones, rules)
    for path, body in ((DNSMASQ_DROPIN, render_dnsmasq(zones, reg)),
                       (PF_ANCHOR, render_pf(zones, reg))):
        os.makedirs(os.path.dirname(path), exist_ok=True)
        tmp = path + ".tmp"
        with open(tmp, "w") as fh:
            fh.write(body)
        os.replace(tmp, path)
        print("wrote %s" % path)
    if not args.no_reload:
        subprocess.run(["/usr/local/sbin/configctl", "dnsmasq", "restart"],
                       capture_output=True, text=True, timeout=60)
        print("reloaded dnsmasq")
    return 0


def cmd_assign(args):
    d = assign(args.mac, args.zone)
    print("%s -> %s" % (args.mac.upper(), d["zone"]))
    return 0


def cmd_reconcile(args):
    reg = reconcile()
    print("%d devices, %d unidentified" % (
        len(reg.get("devices", {})),
        sum(1 for d in reg["devices"].values()
            if d.get("state") == "unidentified")))
    return 0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = ap.add_subparsers(dest="cmd", required=True)
    sub.add_parser("status").set_defaults(fn=cmd_status)
    sub.add_parser("reconcile").set_defaults(fn=cmd_reconcile)
    p = sub.add_parser("devices")
    p.add_argument("--zone")
    p.add_argument("--refresh", action="store_true")
    p.set_defaults(fn=cmd_devices)
    sub.add_parser("plan").set_defaults(fn=cmd_plan)
    p = sub.add_parser("apply")
    p.add_argument("--force", action="store_true")
    p.add_argument("--no-reload", action="store_true")
    p.set_defaults(fn=cmd_apply)
    p = sub.add_parser("assign")
    p.add_argument("mac")
    p.add_argument("zone")
    p.set_defaults(fn=cmd_assign)
    args = ap.parse_args()
    return args.fn(args)


if __name__ == "__main__":
    sys.exit(main())
