package firewall

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/grioghar/flowsight/internal/core"
)

// provider compiles net.block and the dynamic side of app.block into the
// "policy" sub-anchor: one rule per denied port range, one "internet" rule
// per policy, a persistent table per policy that the app-control module
// fills with the addresses of denied applications as it sees them, and
// tables for countries when GeoIP blocking is in use.
type provider struct {
	m *Module
}

func (p *provider) Name() string           { return "pf" }
func (p *provider) Capabilities() []string { return []string{core.CapNetBlock, core.CapAppBlock} }

var slugRe = regexp.MustCompile(`[^a-z0-9_]+`)

func Slug(name string) string { return slugRe.ReplaceAllString(strings.ToLower(name), "_") }

// TableFor returns the pf table holding denied application addresses for a policy.
func TableFor(policyName string) string { return "fs_app_" + Slug(policyName) }

// GeoTableFor returns the pf table holding addresses for a country.
func GeoTableFor(cc string) string { return "fs_geo_" + strings.ToLower(cc) }

func (p *provider) path() string { return filepath.Join(p.m.dir, "policy.conf") }

func (p *provider) Compile(doc *core.PolicyDoc) (core.Artifact, error) {
	res, _ := p.m.ctx.Service("member_resolver").(core.MemberResolver)
	geo, _ := p.m.ctx.Service("geo").(core.GeoService)
	now := time.Now()
	var b strings.Builder
	b.WriteString("# Generated by flowsight-policy. Loaded into anchor flowsight/policy.\n")
	logOpt := ""
	if core.Bool(p.m.ctx.Settings(), "log_blocks", true) {
		logOpt = " log"
	}
	excluded := map[string]bool{}
	for _, c := range doc.ExcludedCIDRs(res) {
		excluded[c] = true
	}
	// Deliberately not defined here: the firewall module keeps it in the
	// root ruleset and anchor rules resolve to it by name.
	local := p.m.LocalTable()
	var rules []string
	tables := 0
	geoTables := map[string]geoSpec{}

	for i := range doc.Policies {
		pol := &doc.Policies[i]
		if !pol.Enabled || !doc.Active(pol.Schedule, now) {
			continue
		}
		needsNet, needsApp := false, false
		for _, r := range pol.Requirements() {
			if r == core.CapNetBlock {
				needsNet = true
			}
			if r == core.CapAppBlock {
				needsApp = true
			}
		}
		if !needsNet && !needsApp {
			continue
		}
		var members []string
		for _, m := range doc.Members(pol, res) {
			if !excluded[m] {
				members = append(members, m)
			}
		}
		if len(members) == 0 {
			continue
		}
		src := "{ " + strings.Join(members, ", ") + " }"
		if len(members) == 1 {
			src = members[0]
		}
		action := "block return" + logOpt + " quick"
		if pol.Action == "monitor" {
			// Monitor: match and count, never drop. pf "match" rules with a
			// label give the same counters without enforcing.
			action = "match" + logOpt
		}
		label := "flowsight:" + pol.Name
		if needsApp {
			tbl := TableFor(pol.Name)
			fmt.Fprintf(&b, "table <%s> persist\n", tbl)
			tables++
			rules = append(rules, fmt.Sprintf("%s from %s to <%s> label \"%s:app\"", action, src, tbl, label))
		}
		if pol.Deny.Internet {
			rules = append(rules, fmt.Sprintf("%s from %s to ! <%s> label \"%s:internet\"", action, src, local, label))
		}
		for _, port := range pol.Deny.Ports {
			pp := strings.ToLower(port)
			proto, rng, _ := strings.Cut(pp, "/")
			rng = strings.ReplaceAll(rng, "-", ":")
			protoClause := "proto " + proto
			if proto == "any" {
				protoClause = "proto { tcp, udp }"
			}
			rules = append(rules, fmt.Sprintf("%s %s from %s to any port %s label \"%s:port\"",
				action, protoClause, src, rng, label))
		}
		// Country denials: one persistent table per denied country, or one
		// per policy holding every country but the allowed ones. The tables
		// are declared here and filled in Apply from the local database.
		if len(pol.Deny.Countries) > 0 || len(pol.Deny.CountriesExcept) > 0 {
			if geo == nil {
				return core.Artifact{}, fmt.Errorf("policy %q denies countries, which needs the country database: Settings › enrich › Country lookup", pol.Name)
			}
			for _, cc := range pol.Deny.Countries {
				tbl := GeoTableFor(cc)
				geoTables[tbl] = geoSpec{Table: tbl, Countries: []string{strings.ToUpper(cc)}}
				rules = append(rules, fmt.Sprintf("%s from %s to <%s> label \"%s:country:%s\"", action, src, tbl, label, strings.ToUpper(cc)))
			}
			if len(pol.Deny.CountriesExcept) > 0 {
				tbl := "fs_geox_" + Slug(pol.Name)
				geoTables[tbl] = geoSpec{Table: tbl, Countries: upperAll(pol.Deny.CountriesExcept), Invert: true}
				rules = append(rules, fmt.Sprintf("%s from %s to <%s> label \"%s:country-except\"", action, src, tbl, label))
			}
		}
	}
	sort.Strings(rules)
	for _, r := range rules {
		b.WriteString(r + "\n")
	}
	if len(geoTables) > 0 {
		names := make([]string, 0, len(geoTables))
		for tbl := range geoTables {
			names = append(names, tbl)
		}
		sort.Strings(names)
		for _, tbl := range names {
			fmt.Fprintf(&b, "table <%s> persist\n", tbl)
			b.WriteString(geoTables[tbl].comment() + "\n")
		}
		tables += len(geoTables)
	}
	return core.Artifact{Files: map[string]string{p.path(): b.String()},
		Note: fmt.Sprintf("%d rule(s), %d table(s)", len(rules), tables)}, nil
}

// geoSpec is what a country table must hold. It is written into the rules
// file as a comment so Apply, and the hourly refresh, can rebuild it from
// the artifact alone.
type geoSpec struct {
	Table     string
	Countries []string
	Invert    bool
}

func (g geoSpec) comment() string {
	list := strings.Join(g.Countries, ",")
	if g.Invert {
		list = "!" + list
	}
	return "# geo-table " + g.Table + " " + list
}

// geoSpecs reads the geo-table comments back out of a rules file.
func geoSpecs(rules string) []geoSpec {
	var out []geoSpec
	for _, l := range strings.Split(rules, "\n") {
		f := strings.Fields(l)
		if len(f) != 4 || f[0] != "#" || f[1] != "geo-table" {
			continue
		}
		g := geoSpec{Table: f[2]}
		list := f[3]
		if strings.HasPrefix(list, "!") {
			g.Invert = true
			list = list[1:]
		}
		g.Countries = strings.Split(list, ",")
		out = append(out, g)
	}
	return out
}

func upperAll(in []string) []string {
	out := make([]string, len(in))
	for i, s := range in {
		out[i] = strings.ToUpper(strings.TrimSpace(s))
	}
	return out
}

func (p *provider) Current() (core.Artifact, error) {
	b, err := os.ReadFile(p.path())
	if err != nil {
		return core.Artifact{Files: map[string]string{p.path(): ""}}, nil
	}
	return core.Artifact{Files: map[string]string{p.path(): string(b)}}, nil
}

func (p *provider) Apply(a core.Artifact) (string, error) {
	rules := a.Files[p.path()]
	// Table contents survive a rules reload because the tables are persist
	// and re-declared; only the rule text changes.
	if err := p.m.LoadAnchor("policy", rules); err != nil {
		return "", err
	}

	if specs := geoSpecs(rules); len(specs) > 0 {
		// Filling can take a while on a small gateway (one pass over the
		// country database per table), so it runs off the request; the
		// status route says when it is done.
		p.m.fillGeoTablesAsync(specs, true)
	}

	n := 0
	for _, l := range strings.Split(rules, "\n") {
		if strings.HasPrefix(l, "block") || strings.HasPrefix(l, "match") {
			n++
		}
	}
	return fmt.Sprintf("anchor flowsight/policy loaded with %d rule(s)", n), nil
}

// populateGeoTables fills the country tables the policy rules reference,
// each in one pass over the local database. With force false a table is
// left alone when it was already filled from the current database build.
// For "every country except" tables the home country is always allowed.
func (m *Module) populateGeoTables(specs []geoSpec, force bool) error {
	geo, _ := m.ctx.Service("geo").(core.GeoService)
	if geo == nil {
		return fmt.Errorf("country database not available")
	}
	epoch := geo.DatabaseEpoch()
	if epoch == 0 {
		return fmt.Errorf("country database not loaded yet")
	}
	home := ""
	if h, ok := m.ctx.Service("home").(core.HomeService); ok {
		home = h.HomeCountry()
	}
	// Anycast ranges are left out of every country table: they are served
	// from a nearby site whatever country they are registered in.
	var skip func(prefix string) bool
	if anyc, ok := m.ctx.Service("anycast").(core.AnycastLookup); ok {
		skip = func(prefix string) bool {
			ip, _, _ := strings.Cut(prefix, "/")
			a, _ := anyc.Anycast(ip)
			return a
		}
	}
	var firstErr error
	for _, g := range specs {
		m.mu.Lock()
		cur := m.geoTables[g.Table]
		m.mu.Unlock()
		if !force && cur != nil && cur.Epoch == epoch {
			continue
		}
		ccs := g.Countries
		if g.Invert && home != "" {
			ccs = append(append([]string(nil), ccs...), home)
		}
		prefixes, skipped, err := geo.NetworksFor(ccs, g.Invert, skip)
		if err == nil {
			err = m.ReplaceTable("policy", g.Table, prefixes)
		}
		if err != nil {
			if firstErr == nil {
				firstErr = fmt.Errorf("%s: %w", g.Table, err)
			}
			continue
		}
		m.mu.Lock()
		m.geoTables[g.Table] = &TableInfo{Name: g.Table, Countries: ccs, Invert: g.Invert, Prefixes: len(prefixes), SkippedAnycast: skipped, Epoch: epoch, Updated: time.Now().Unix()}
		m.mu.Unlock()
	}
	return firstErr
}

// refreshGeoTables follows the monthly database update: tables filled from
// an older build are rebuilt, and a fresh process fills them once.
func (m *Module) refreshGeoTables() error {
	a, err := (&provider{m: m}).Current()
	if err != nil {
		return nil
	}
	specs := geoSpecs(a.Files[filepath.Join(m.dir, "policy.conf")])
	if len(specs) == 0 {
		return nil
	}
	return m.populateGeoTables(specs, false)
}

// fillGeoTablesAsync runs populateGeoTables in the background, one at a time.
func (m *Module) fillGeoTablesAsync(specs []geoSpec, force bool) {
	m.mu.Lock()
	if m.geoFilling {
		m.geoPending = true
		m.mu.Unlock()
		return
	}
	m.geoFilling = true
	m.mu.Unlock()
	go func() {
		defer func() {
			m.mu.Lock()
			m.geoFilling = false
			again := m.geoPending
			m.geoPending = false
			m.mu.Unlock()
			if again {
				_ = m.refreshGeoTables()
			}
		}()
		if err := m.populateGeoTables(specs, force); err != nil {
			m.ctx.Event("firewall", "country tables not filled", map[string]any{"error": err.Error()})
		}
	}()
}
