package firewall

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/grioghar/flowsight/internal/core"
)

// provider compiles net.block and the dynamic side of app.block into the
// "policy" sub-anchor: one rule per denied port range, one "internet" rule
// per policy, a persistent table per policy that the app-control module
// fills with the addresses of denied applications as it sees them, and
// tables for countries when GeoIP blocking is in use.
type provider struct {
	m *Module
}

func (p *provider) Name() string           { return "pf" }
func (p *provider) Capabilities() []string { return []string{core.CapNetBlock, core.CapAppBlock} }

var slugRe = regexp.MustCompile(`[^a-z0-9_]+`)

func Slug(name string) string { return slugRe.ReplaceAllString(strings.ToLower(name), "_") }

// TableFor returns the pf table holding denied application addresses for a policy.
func TableFor(policyName string) string { return "fs_app_" + Slug(policyName) }

// GeoTableFor returns the pf table holding addresses for a country.
func GeoTableFor(cc string) string { return "fs_geo_" + strings.ToLower(cc) }

func (p *provider) path() string { return filepath.Join(p.m.dir, "policy.conf") }

func (p *provider) Compile(doc *core.PolicyDoc) (core.Artifact, error) {
	res, _ := p.m.ctx.Service("member_resolver").(core.MemberResolver)
	geo, _ := p.m.ctx.Service("geo").(core.GeoService)
	now := time.Now()
	var b strings.Builder
	b.WriteString("# Generated by flowsight-policy. Loaded into anchor flowsight/policy.\n")
	logOpt := ""
	if core.Bool(p.m.ctx.Settings(), "log_blocks", true) {
		logOpt = " log"
	}
	excluded := map[string]bool{}
	for _, c := range doc.ExcludedCIDRs(res) {
		excluded[c] = true
	}
	// Deliberately not defined here: the firewall module keeps it in the
	// root ruleset and anchor rules resolve to it by name.
	local := p.m.LocalTable()
	var rules []string
	tables := 0
	geoTables := map[string]bool{} // Track which geo tables are needed

	for i := range doc.Policies {
		pol := &doc.Policies[i]
		if !pol.Enabled || !doc.Active(pol.Schedule, now) {
			continue
		}
		needsNet, needsApp := false, false
		for _, r := range pol.Requirements() {
			if r == core.CapNetBlock {
				needsNet = true
			}
			if r == core.CapAppBlock {
				needsApp = true
			}
		}
		if !needsNet && !needsApp {
			continue
		}
		var members []string
		for _, m := range doc.Members(pol, res) {
			if !excluded[m] {
				members = append(members, m)
			}
		}
		if len(members) == 0 {
			continue
		}
		src := "{ " + strings.Join(members, ", ") + " }"
		if len(members) == 1 {
			src = members[0]
		}
		action := "block return" + logOpt + " quick"
		if pol.Action == "monitor" {
			// Monitor: match and count, never drop. pf "match" rules with a
			// label give the same counters without enforcing.
			action = "match" + logOpt
		}
		label := "flowsight:" + pol.Name
		if needsApp {
			tbl := TableFor(pol.Name)
			fmt.Fprintf(&b, "table <%s> persist\n", tbl)
			tables++
			rules = append(rules, fmt.Sprintf("%s from %s to <%s> label \"%s:app\"", action, src, tbl, label))
		}
		if pol.Deny.Internet {
			rules = append(rules, fmt.Sprintf("%s from %s to ! <%s> label \"%s:internet\"", action, src, local, label))
		}
		for _, port := range pol.Deny.Ports {
			pp := strings.ToLower(port)
			proto, rng, _ := strings.Cut(pp, "/")
			rng = strings.ReplaceAll(rng, "-", ":")
			protoClause := "proto " + proto
			if proto == "any" {
				protoClause = "proto { tcp, udp }"
			}
			rules = append(rules, fmt.Sprintf("%s %s from %s to any port %s label \"%s:port\"",
				action, protoClause, src, rng, label))
		}
		// Handle country denials.
		if len(pol.Deny.Countries) > 0 {
			if geo == nil {
				return core.Artifact{}, fmt.Errorf("policy %q denies countries but GeoIP service is not available", pol.Name)
			}
			for _, cc := range pol.Deny.Countries {
				tbl := GeoTableFor(cc)
				geoTables[tbl] = true
				rules = append(rules, fmt.Sprintf("%s from %s to <%s> label \"%s:country:%s\"", action, src, tbl, label, cc))
			}
		}
	}
	sort.Strings(rules)
	for _, r := range rules {
		b.WriteString(r + "\n")
	}
	// Declare geo tables (they will be populated separately).
	if len(geoTables) > 0 {
		b.WriteString("# GeoIP country tables\n")
		var geoTableList []string
		for tbl := range geoTables {
			geoTableList = append(geoTableList, tbl)
		}
		sort.Strings(geoTableList)
		for _, tbl := range geoTableList {
			fmt.Fprintf(&b, "table <%s> persist file \"%s/geo-%s.txt\"\n", tbl, p.m.dir, strings.TrimPrefix(tbl, "fs_geo_"))
		}
		tables += len(geoTables)
	}
	return core.Artifact{Files: map[string]string{p.path(): b.String()},
		Note: fmt.Sprintf("%d rule(s), %d app/geo table(s)", len(rules), tables)}, nil
}

func (p *provider) Current() (core.Artifact, error) {
	b, err := os.ReadFile(p.path())
	if err != nil {
		return core.Artifact{Files: map[string]string{p.path(): ""}}, nil
	}
	return core.Artifact{Files: map[string]string{p.path(): string(b)}}, nil
}

func (p *provider) Apply(a core.Artifact) (string, error) {
	rules := a.Files[p.path()]
	// Table contents survive a rules reload because the tables are persist
	// and re-declared; only the rule text changes.
	if err := p.m.LoadAnchor("policy", rules); err != nil {
		return "", err
	}
	n := 0
	for _, l := range strings.Split(rules, "\n") {
		if strings.HasPrefix(l, "block") || strings.HasPrefix(l, "match") {
			n++
		}
	}
	return fmt.Sprintf("anchor flowsight/policy loaded with %d rule(s)", n), nil
}
