package qos

// Turning the plan into pf rules.
//
// Two things about pf decide the shape of this file.
//
// Everything is matched on the LAN interface, not the WAN. On the way out
// through the WAN the source address has already been translated, so a rule
// naming a device on this network cannot match it there. On the LAN side both
// ends are still themselves.
//
// And a queue is assigned once, when the state is created, for both
// directions of that state. Writing one rule for "in" and another for "out"
// looks right and does not work: the reply travels back through the state the
// first rule made and never reaches the second. The two-argument form exists
// for exactly this, so each rule matches the direction that opens the
// connection and names both queues at once:
//
//	match in on <lan> ... dnqueue(<upload>, <download>)
//
// Measured on a test gateway with the wrong shape: the inbound rule saw 4197
// packets and the outbound rule 49, and nothing was shaped.
//
// The rules are "match" rather than "pass", which in pf applies the queue and
// carries on rather than deciding the packet's fate. Shaping should never be
// able to let something through that policy would have blocked.

import (
	"fmt"
	"strings"
)

// anchorInput is what render needs that does not come from the rules.
type anchorInput struct {
	LAN          string
	Rules        []Rule
	Addrs        map[string][]string // domain rule -> addresses seen for it
	DefaultClass Class
	Ceilings     map[string]ceiling // rule match -> its two pipes
	// IsLocal decides which end of a conversation an address rule names. The
	// same literal can mean either: 192.168.1.178 is a device on this network
	// and needs the rules written one way round, while 203.0.113.9 is
	// something out there and needs them the other. Guessing wrong shapes the
	// opposite half of every matching conversation and looks fine doing it.
	IsLocal func(string) bool
}

// tableName is a pf table per rule, named from its position so that two rules
// matching similar things never collide.
func tableName(i int) string { return fmt.Sprintf("qos_r%d", i) }

// render returns the anchor text and the table contents to load with it.
func render(in anchorInput) (string, map[string][]string) {
	var b strings.Builder
	tables := map[string][]string{}
	w := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	w("# Generated by FlowSight. Traffic shaping: the queue that decides what")
	w("# waits is moved onto this firewall, and these rules decide who waits.")
	w("# Matched on the LAN side, where addresses are not yet translated.")
	w("")
	if in.LAN == "" || len(valid(in.Rules)) == 0 && in.DefaultClass == "" {
		return "", tables
	}

	rules := valid(in.Rules)
	for i, r := range rules {
		addrs := []string{r.Match}
		if !r.IsHost {
			addrs = in.Addrs[r.Match]
		}
		if len(addrs) == 0 {
			continue // a name nothing has resolved yet matches nothing, quietly
		}
		tables[tableName(i)] = addrs
		w("table <%s> persist", tableName(i))
	}
	w("")

	// The default first, so a more specific rule later overrides it: pf takes
	// the last matching rule when none of them is quick, and none is.
	if in.DefaultClass != "" {
		w("# Everything starts in the %s class.", in.DefaultClass)
		w("match in on %s all dnqueue(%d)", in.LAN, classQueue(in.DefaultClass, false))
		w("match out on %s all dnqueue(%d)", in.LAN, classQueue(in.DefaultClass, true))
		w("")
	}

	for i, r := range rules {
		if _, ok := tables[tableName(i)]; !ok {
			continue
		}
		t := tableName(i)
		side := "the far end"
		if r.IsHost && (in.IsLocal == nil || in.IsLocal(r.Match)) {
			side = "this device"
		}
		w("# %s: %s", strings.TrimSpace(r.Raw), side)
		// A device here is the source going out and the destination coming
		// back; something out there is the reverse. A name is always out
		// there. An address is whichever side of the local networks it falls.
		here := r.IsHost && (in.IsLocal == nil || in.IsLocal(r.Match))
		// Each direction needs its own rule. A queue named on a rule that
		// specifies "in" or "out" applies only to that direction, so the pair
		// form buys nothing here and the reply would go unshaped.
		sel, rev := "from <"+t+"> to any", "from any to <"+t+">"
		if !here {
			sel, rev = "from any to <"+t+">", "from <"+t+"> to any"
		}
		if r.Class != "" {
			w("match in on %s %s dnqueue(%d)", in.LAN, sel, classQueue(r.Class, false))
			w("match out on %s %s dnqueue(%d)", in.LAN, rev, classQueue(r.Class, true))
		}
		if c, ok := in.Ceilings[r.Match]; ok && r.Ceiling > 0 {
			w("match in on %s %s dnpipe(%d)", in.LAN, sel, c.UpPipe)
			w("match out on %s %s dnpipe(%d)", in.LAN, rev, c.DownPipe)
		}
		w("")
	}
	return b.String(), tables
}
