package dns

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/grioghar/flowsight/internal/core"
)

// provider compiles the policy document into Unbound views.
//
// A view binds a set of local-zone entries to specific client addresses via
// access-control-view, which is exactly what "deny these domains for the kids"
// means. Denied names answer REFUSED so the block is attributable in the log.
// Safe search is a CNAME-style redirect (local-data) to the vendors' enforced
// endpoints, which is how every DNS-based safe-search product works.
type provider struct {
	m *Module
}

func (p *provider) Name() string           { return "unbound" }
func (p *provider) Capabilities() []string { return []string{core.CapDNSBlock} }

var viewNameRe = regexp.MustCompile(`[^a-z0-9-]+`)

const header = "# Generated by flowsight-policy. Do not edit: the policy document is the source of truth.\n"

// Safe-search targets. The redirect names are what the vendors publish for
// DNS enforcement; the addresses are resolved by Unbound itself at query time
// through the CNAME, so nothing here goes stale.
var safeSearch = map[string]string{
	"www.google.com":     "forcesafesearch.google.com",
	"www.bing.com":       "strict.bing.com",
	"duckduckgo.com":     "safe.duckduckgo.com",
	"www.duckduckgo.com": "safe.duckduckgo.com",
}

var youtubeHosts = []string{"www.youtube.com", "m.youtube.com", "youtubei.googleapis.com",
	"youtube.googleapis.com", "www.youtube-nocookie.com"}

func (p *provider) Compile(doc *core.PolicyDoc) (core.Artifact, error) {
	res, _ := p.m.ctx.Service("member_resolver").(core.MemberResolver)
	cats, _ := p.m.ctx.Service("categories").(core.Categories)
	maxDomains := core.Int(p.m.ctx.Settings(), "max_view_domains", 200000)
	mode := doc.Options.DNSBlockMode
	if mode == "" {
		mode = "refused"
	}
	zoneType := map[string]string{"refused": "always_refuse", "nxdomain": "always_nxdomain",
		"null": "always_null"}[mode]

	var b strings.Builder
	b.WriteString(header)
	var acls []string
	var compiled []compiledPolicy
	now := time.Now()
	excluded := doc.ExcludedCIDRs(res)
	exclDomains := map[string]bool{}
	for _, d := range doc.Exclusions.Domains {
		exclDomains[d] = true
	}

	for i := range doc.Policies {
		pol := &doc.Policies[i]
		if !pol.Enabled || pol.Action != "block" || !doc.Active(pol.Schedule, now) {
			continue
		}
		needs := false
		for _, r := range pol.Requirements() {
			if r == core.CapDNSBlock {
				needs = true
			}
		}
		if !needs {
			continue
		}
		members := doc.Members(pol, res)
		if len(members) == 0 {
			return core.Artifact{}, fmt.Errorf("policy %q resolves to no addresses", pol.Name)
		}
		domains := map[string]bool{}
		for _, d := range pol.Deny.Domains {
			domains[d] = true
		}
		for _, c := range pol.Deny.Categories {
			if cats == nil {
				return core.Artifact{}, fmt.Errorf("policy %q uses category %q but the categories module is not loaded", pol.Name, c)
			}
			list, err := cats.Domains(c)
			if err != nil {
				return core.Artifact{}, fmt.Errorf("policy %q: %v", pol.Name, err)
			}
			for _, d := range list {
				domains[d] = true
			}
		}
		allow := map[string]bool{}
		for _, d := range pol.Allow.Domains {
			allow[d] = true
		}
		for d := range domains {
			if allow[d] || exclDomains[d] {
				delete(domains, d)
			}
		}
		if len(domains) > maxDomains {
			return core.Artifact{}, fmt.Errorf("policy %q resolves to %d domains, over the %d limit: a view that large "+
				"degrades the resolver for everyone. Use a smaller category or block it resolver-wide.",
				pol.Name, len(domains), maxDomains)
		}
		view := "flowsight-" + viewNameRe.ReplaceAllString(strings.ToLower(pol.Name), "-")
		fmt.Fprintf(&b, "view:\n    name: \"%s\"\n    view-first: yes\n", view)
		if pol.Description != "" {
			fmt.Fprintf(&b, "    # %s\n", strings.ReplaceAll(pol.Description, "\n", " "))
		}
		for _, d := range sortedKeys(domains) {
			fmt.Fprintf(&b, "    local-zone: \"%s.\" %s\n", d, zoneType)
		}
		for _, t := range pol.Deny.TLDs {
			fmt.Fprintf(&b, "    local-zone: \"%s.\" %s\n", t, zoneType)
		}
		for _, d := range pol.Allow.Domains {
			// An allow inside a denied zone needs a transparent zone to punch through.
			fmt.Fprintf(&b, "    local-zone: \"%s.\" transparent\n", d)
		}
		if pol.SafeSearch {
			for host, target := range safeSearch {
				fmt.Fprintf(&b, "    local-zone: \"%s.\" redirect\n    local-data: \"%s. CNAME %s.\"\n", host, host, target)
			}
		}
		if pol.YouTube != "" {
			target := "restrict.youtube.com"
			if pol.YouTube == "moderate" {
				target = "restrictmoderate.youtube.com"
			}
			for _, h := range youtubeHosts {
				fmt.Fprintf(&b, "    local-zone: \"%s.\" redirect\n    local-data: \"%s. CNAME %s.\"\n", h, h, target)
			}
		}
		b.WriteString("\n")
		var nets []*net.IPNet
		for _, m := range members {
			if isExcluded(m, excluded) {
				continue
			}
			acls = append(acls, fmt.Sprintf("    access-control-view: %s %s", m, view))
			if _, n, err := net.ParseCIDR(m); err == nil {
				nets = append(nets, n)
			}
		}
		compiled = append(compiled, compiledPolicy{name: pol.Name, members: nets, domains: domains})
	}
	if len(acls) > 0 {
		b.WriteString("server:\n")
		sort.Strings(acls)
		b.WriteString(strings.Join(acls, "\n"))
		b.WriteString("\n")
	}
	p.m.mu.Lock()
	p.m.compiled = compiled
	p.m.mu.Unlock()
	return core.Artifact{Files: map[string]string{p.path(): b.String()},
		Note: fmt.Sprintf("%d view(s)", len(compiled))}, nil
}

func isExcluded(member string, excluded []string) bool {
	for _, e := range excluded {
		if e == member {
			return true
		}
	}
	return false
}

func (p *provider) path() string {
	pl := p.m.ctx.Platform
	if pl.IsOPNsense() {
		return "/usr/local/etc/unbound.opnsense.d/flowsight-policy.conf"
	}
	return pl.UnboundInclude
}

func (p *provider) Current() (core.Artifact, error) {
	b, err := os.ReadFile(p.path())
	if err != nil {
		if os.IsNotExist(err) {
			return core.Artifact{Files: map[string]string{p.path(): ""}}, nil
		}
		return core.Artifact{}, err
	}
	return core.Artifact{Files: map[string]string{p.path(): string(b)}}, nil
}

// Apply writes the include atomically, validates the whole resolver config,
// reverts on rejection, and reloads. A failed reload also reverts: leaving a
// rejected include in place would take DNS down on the next restart.
func (p *provider) Apply(a core.Artifact) (string, error) {
	path := p.path()
	text := a.Files[path]
	pl := p.m.ctx.Platform
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return "", err
	}
	var backup []byte
	had := false
	if cur, err := os.ReadFile(path); err == nil {
		backup, had = cur, true
	}
	revert := func() {
		if had {
			_ = os.WriteFile(path, backup, 0o644)
		} else {
			_ = os.Remove(path)
		}
	}
	if strings.TrimSpace(text) == strings.TrimSpace(header) || strings.TrimSpace(text) == "" {
		// Nothing to enforce: remove the include rather than leave an empty one.
		_ = os.Remove(path)
	} else {
		if err := os.WriteFile(path+".tmp", []byte(text), 0o644); err != nil {
			return "", err
		}
		if err := os.Rename(path+".tmp", path); err != nil {
			return "", err
		}
	}
	if out, err := pl.UnboundCheck(); err != nil {
		revert()
		return "", fmt.Errorf("unbound-checkconf rejected the generated config, reverted: %s", firstLines(out, 5))
	}
	if out, err := pl.Service("unbound", "reload"); err != nil {
		revert()
		_, _ = pl.Service("unbound", "reload")
		return "", fmt.Errorf("unbound reload failed, reverted: %s", firstLines(out, 5))
	}
	sum := sha256.Sum256([]byte(text))
	return "unbound reloaded (" + hex.EncodeToString(sum[:6]) + ")", nil
}

func firstLines(s string, n int) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, " | ")
}
