package dns

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"hash/fnv"
	"net"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"time"

	"github.com/grioghar/flowsight/internal/core"
)

// provider compiles the policy document onto Unbound.
//
// Domain, category and TLD denials become one Response Policy Zone per
// policy, bound to the policy's clients with access-control tags. RPZ is
// built for exactly this: a zone of hundreds of thousands of names costs
// little, is shared across threads, and every hit is logged with the zone's
// name, so a FlowSight block is attributable in the resolver log without
// guessing from an rcode. Safe search and YouTube restrictions, which need a
// CNAME answer rather than a refusal, use a per-policy view.
type provider struct {
	m *Module
}

func (p *provider) Name() string           { return "unbound" }
func (p *provider) Capabilities() []string { return []string{core.CapDNSBlock} }

var slugRe = regexp.MustCompile(`[^a-z0-9-]+`)

const header = "# Generated by flowsight-policy. Do not edit: the policy document is the source of truth.\n"

// Safe-search targets published by the vendors for DNS enforcement. Unbound
// resolves the CNAME target itself at query time, so nothing here goes stale.
var safeSearch = map[string]string{
	"www.google.com":     "forcesafesearch.google.com",
	"www.bing.com":       "strict.bing.com",
	"duckduckgo.com":     "safe.duckduckgo.com",
	"www.duckduckgo.com": "safe.duckduckgo.com",
}

var youtubeHosts = []string{"www.youtube.com", "m.youtube.com", "youtubei.googleapis.com",
	"youtube.googleapis.com", "www.youtube-nocookie.com"}

func slug(name string) string { return slugRe.ReplaceAllString(strings.ToLower(name), "-") }

func (p *provider) dir() string {
	if p.m.ctx.Platform.IsOPNsense() {
		return "/var/unbound/etc"
	}
	return filepath.Dir(p.m.ctx.Platform.UnboundInclude)
}

func (p *provider) confPath() string { return filepath.Join(p.dir(), "flowsight-policy.conf") }

func (p *provider) Compile(doc *core.PolicyDoc) (core.Artifact, error) {
	res, _ := p.m.ctx.Service("member_resolver").(core.MemberResolver)
	cats, _ := p.m.ctx.Service("categories").(core.Categories)
	maxDomains := core.Int(p.m.ctx.Settings(), "max_zone_domains", 1500000)
	mode := doc.Options.DNSBlockMode
	if mode == "" {
		mode = "nxdomain"
	}
	rpzAction := map[string]string{"refused": "nxdomain", "nxdomain": "nxdomain", "null": "nodata"}[mode]

	files := map[string]string{}
	var conf strings.Builder
	conf.WriteString(header)
	var tags, acls, rpzs, views []string
	var compiled []compiledPolicy
	now := time.Now()
	excluded := map[string]bool{}
	for _, c := range doc.ExcludedCIDRs(res) {
		excluded[c] = true
	}
	exclDomains := map[string]bool{}
	for _, d := range doc.Exclusions.Domains {
		exclDomains[d] = true
	}

	for i := range doc.Policies {
		pol := &doc.Policies[i]
		if !pol.Enabled || pol.Action != "block" || !doc.Active(pol.Schedule, now) {
			continue
		}
		wants := false
		for _, r := range pol.Requirements() {
			if r == core.CapDNSBlock {
				wants = true
			}
		}
		if !wants {
			continue
		}
		var members []string
		for _, m := range doc.Members(pol, res) {
			if !excluded[m] || pol.Match.EvenExcluded {
				members = append(members, m)
			}
		}
		if len(members) == 0 {
			return core.Artifact{}, fmt.Errorf("policy %q resolves to no addresses", pol.Name)
		}
		id := slug(pol.Name)
		tag := "fs-" + id

		// --- RPZ zone: domains, categories, TLDs, allow exceptions -------
		domains := map[string]bool{}
		for _, d := range pol.Deny.Domains {
			domains[d] = true
		}
		for _, c := range pol.Deny.Categories {
			if cats == nil {
				return core.Artifact{}, fmt.Errorf("policy %q uses category %q but the categories module is not loaded", pol.Name, c)
			}
			list, err := cats.Domains(c)
			if err != nil {
				return core.Artifact{}, fmt.Errorf("policy %q: %v", pol.Name, err)
			}
			for _, d := range list {
				domains[d] = true
			}
		}
		for d := range domains {
			if exclDomains[d] {
				delete(domains, d)
			}
		}
		for _, d := range pol.Allow.Domains {
			delete(domains, d)
		}
		if len(domains) > maxDomains {
			return core.Artifact{}, fmt.Errorf("policy %q resolves to %d domains, over the %d limit; raise "+
				"max_zone_domains in the dns module if the firewall has the memory", pol.Name, len(domains), maxDomains)
		}
		var nets []*net.IPNet
		for _, m := range members {
			if _, n, err := net.ParseCIDR(m); err == nil {
				nets = append(nets, n)
			}
		}
		if len(domains) > 0 || len(pol.Deny.TLDs) > 0 {
			// The SOA serial must be a function of the zone's content, not of
			// the clock: a clock-derived serial made every compile differ and
			// the reconciler reloaded Unbound every minute for nothing.
			var body strings.Builder
			for _, d := range pol.Allow.Domains {
				fmt.Fprintf(&body, "%s CNAME rpz-passthru.\n*.%s CNAME rpz-passthru.\n", d, d)
			}
			for _, d := range sortedKeys(domains) {
				fmt.Fprintf(&body, "%s CNAME .\n*.%s CNAME .\n", d, d)
			}
			for _, t := range pol.Deny.TLDs {
				fmt.Fprintf(&body, "%s CNAME .\n*.%s CNAME .\n", t, t)
			}
			h := fnv.New32a()
			_, _ = h.Write([]byte(body.String()))
			serial := h.Sum32() & 0x7fffffff
			var z strings.Builder
			fmt.Fprintf(&z, "$TTL 300\n@ SOA localhost. flowsight.localhost. %d 3600 900 604800 300\n@ NS localhost.\n", serial)
			z.WriteString(body.String())
			zonePath := filepath.Join(p.dir(), "flowsight-"+id+".rpz")
			files[zonePath] = z.String()
			rpzs = append(rpzs, fmt.Sprintf("rpz:\n    name: \"flowsight-%s.rpz\"\n    zonefile: \"%s\"\n"+
				"    rpz-action-override: %s\n    rpz-log: yes\n    rpz-log-name: \"%s\"\n    tags: \"%s\"\n",
				id, zonePath, rpzAction, pol.Name, tag))
			tags = append(tags, tag)
			for _, m := range members {
				acls = append(acls, fmt.Sprintf("    access-control-tag: %s \"%s\"", m, tag))
			}
		}

		// --- View: safe search and YouTube need CNAME answers -------------
		if pol.SafeSearch || pol.YouTube != "" {
			var v strings.Builder
			view := "flowsight-" + id
			fmt.Fprintf(&v, "view:\n    name: \"%s\"\n    view-first: yes\n", view)
			if pol.SafeSearch {
				for _, host := range sortedStrKeys(safeSearch) {
					fmt.Fprintf(&v, "    local-zone: \"%s.\" redirect\n    local-data: \"%s. CNAME %s.\"\n",
						host, host, safeSearch[host])
				}
			}
			if pol.YouTube != "" {
				target := "restrict.youtube.com"
				if pol.YouTube == "moderate" {
					target = "restrictmoderate.youtube.com"
				}
				for _, h := range youtubeHosts {
					fmt.Fprintf(&v, "    local-zone: \"%s.\" redirect\n    local-data: \"%s. CNAME %s.\"\n", h, h, target)
				}
			}
			views = append(views, v.String())
			for _, m := range members {
				acls = append(acls, fmt.Sprintf("    access-control-view: %s %s", m, view))
			}
		}
		compiled = append(compiled, compiledPolicy{name: pol.Name, members: nets, domains: domains})
	}

	if len(tags) > 0 || len(acls) > 0 {
		conf.WriteString("server:\n")
		if len(rpzs) > 0 {
			// RPZ needs the respip module. Derive the line from the resolver's
			// own generated config so a later change there (DNSSEC on, for
			// instance) is carried over on the next reconcile rather than
			// silently overridden by a stale copy here.
			fmt.Fprintf(&conf, "    module-config: \"%s\"\n", p.moduleConfig())
		}
		if len(tags) > 0 {
			sort.Strings(tags)
			fmt.Fprintf(&conf, "    define-tag: \"%s\"\n", strings.Join(tags, " "))
		}
		sort.Strings(acls)
		for _, a := range acls {
			conf.WriteString(a + "\n")
		}
		conf.WriteString("\n")
	}
	for _, r := range rpzs {
		conf.WriteString(r + "\n")
	}
	for _, v := range views {
		conf.WriteString(v + "\n")
	}
	if len(rpzs) > 0 || len(views) > 0 {
		files[p.confPath()] = conf.String()
	} else {
		files[p.confPath()] = ""
	}
	p.m.mu.Lock()
	p.m.compiled = compiled
	p.m.mu.Unlock()
	return core.Artifact{Files: files, Note: fmt.Sprintf("%d zone(s), %d view(s)", len(rpzs), len(views))}, nil
}

// moduleConfig returns the resolver's module-config with respip inserted
// before the iterator.
func (p *provider) moduleConfig() string {
	base := "validator iterator"
	if b, err := os.ReadFile(p.m.ctx.Platform.UnboundConfig); err == nil {
		for _, line := range strings.Split(string(b), "\n") {
			t := strings.TrimSpace(line)
			if strings.HasPrefix(t, "module-config:") {
				v := strings.TrimSpace(strings.TrimPrefix(t, "module-config:"))
				base = strings.Trim(v, "\"")
			}
		}
	}
	mods := strings.Fields(base)
	for _, m := range mods {
		if m == "respip" {
			return strings.Join(mods, " ")
		}
	}
	var out []string
	for _, m := range mods {
		if m == "iterator" {
			out = append(out, "respip")
		}
		out = append(out, m)
	}
	return strings.Join(out, " ")
}

func sortedStrKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// Current reads whatever FlowSight files are in place now.
func (p *provider) Current() (core.Artifact, error) {
	files := map[string]string{}
	entries, _ := os.ReadDir(p.dir())
	for _, e := range entries {
		n := e.Name()
		if strings.HasPrefix(n, "flowsight-") && (strings.HasSuffix(n, ".rpz") || n == "flowsight-policy.conf") {
			b, err := os.ReadFile(filepath.Join(p.dir(), n))
			if err == nil {
				files[filepath.Join(p.dir(), n)] = string(b)
			}
		}
	}
	if _, ok := files[p.confPath()]; !ok {
		files[p.confPath()] = ""
	}
	return core.Artifact{Files: files}, nil
}

// persistentDir is where OPNsense keeps includes it copies into the chroot on
// every reconfigure; a copy there survives the GUI regenerating the resolver.
func (p *provider) persistentDir() string {
	if p.m.ctx.Platform.IsOPNsense() {
		return "/usr/local/etc/unbound.opnsense.d"
	}
	return ""
}

// Apply writes every file atomically, removes stale ones, validates the whole
// resolver configuration, reverts on rejection, and reloads. A failed reload
// also reverts: a rejected include left in place would take DNS down on the
// next restart, and on a gateway that is the whole network.
func (p *provider) Apply(a core.Artifact) (string, error) {
	pl := p.m.ctx.Platform
	current, _ := p.Current()
	backup := current.Files
	dirs := []string{p.dir()}
	if d := p.persistentDir(); d != "" {
		dirs = append(dirs, d)
	}
	write := func(files map[string]string) error {
		for _, dir := range dirs {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return err
			}
			for path, text := range files {
				target := filepath.Join(dir, filepath.Base(path))
				if strings.TrimSpace(text) == "" || strings.TrimSpace(text) == strings.TrimSpace(header) {
					_ = os.Remove(target)
					continue
				}
				if err := os.WriteFile(target+".tmp", []byte(text), 0o644); err != nil {
					return err
				}
				if err := os.Rename(target+".tmp", target); err != nil {
					return err
				}
			}
			entries, _ := os.ReadDir(dir)
			for _, e := range entries {
				n := e.Name()
				if !strings.HasPrefix(n, "flowsight-") || n == "flowsight-logging.conf" {
					continue
				}
				if text, keep := files[filepath.Join(p.dir(), n)]; !keep || strings.TrimSpace(text) == "" {
					_ = os.Remove(filepath.Join(dir, n))
				}
			}
		}
		return nil
	}
	if err := write(a.Files); err != nil {
		_ = write(backup)
		return "", err
	}
	if out, err := pl.UnboundCheck(); err != nil {
		_ = write(backup)
		return "", fmt.Errorf("unbound-checkconf rejected the generated config, reverted: %s", firstLines(out, 5))
	}
	if out, err := pl.Service("unbound", "reload"); err != nil {
		_ = write(backup)
		_, _ = pl.Service("unbound", "reload")
		return "", fmt.Errorf("unbound reload failed, reverted: %s", firstLines(out, 5))
	}
	var all strings.Builder
	for _, k := range sortedFileKeys(a.Files) {
		all.WriteString(a.Files[k])
	}
	sum := sha256.Sum256([]byte(all.String()))
	return "unbound reloaded (" + hex.EncodeToString(sum[:6]) + ")", nil
}

func sortedFileKeys(m map[string]string) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

func firstLines(s string, n int) string {
	lines := strings.Split(strings.TrimSpace(s), "\n")
	if len(lines) > n {
		lines = lines[:n]
	}
	return strings.Join(lines, " | ")
}
