package web

import (
	"fmt"
	"net"
	"sort"
	"strings"

	"github.com/grioghar/flowsight/internal/core"
)

// squidConf renders the configuration of the proxy instance FlowSight owns.
//
// The instance is transparent only: pf redirects port 80 and 443 from the
// selected networks to its two loopback listeners. TLS is peeked for the
// server name and then spliced (relayed untouched) unless a policy asks for
// inspection of that client, in which case the connection is bumped with the
// FlowSight CA. Denied names are terminated at the ClientHello, before a
// single application byte, which is what makes web blocking inline.
type squidParams struct {
	HTTPPort, HTTPSPort int
	Dir                 string // config dir; ACL files live here
	LogDir              string
	RunDir              string
	User                string
	Group               string
	LocalNets           []string
	CAPath              string // combined cert+key PEM; "" disables bumping
	CertDB              string
	CertgenBin          string
	BlockPageURL        string
	PeekServerCert      bool // peek at step 2 (see certificates) before splicing
	Policies            []squidPolicy
	Exclusions          []string // client CIDRs never touched
	ExclDomains         []string
	DNSServers          []string
	Workers             int
	// DeepPort, when set, is a loopback ICAP service that is handed each
	// decrypted request and response for DeepClients and DeepNames (empty
	// means every inspected
	// client or name). Pinned names never go there: they are never opened.
	DeepPort    int
	DeepPreview int
	DeepClients []string
	DeepNames   []string
	// V6Listener is an address the firewall owns on the LAN (a unique local
	// address works well); pf cannot redirect LAN traffic to [::1].
	V6Listener string
}

type squidPolicy struct {
	ID       string
	Members  []string
	Monitor  bool
	Domains  []string // denied, with subdomains
	Allow    []string
	Inspect  bool
	Bypass   []string
	Category string
}

func (p squidParams) render() (string, map[string]string) {
	files := map[string]string{}
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	w("# Generated by flowsight. The web module owns this proxy instance; edit policy, not this file.")
	w("pid_filename %s/squid.pid", p.RunDir)
	w("cache_effective_user %s", p.User)
	if p.Group != "" {
		// /dev/pf is group-readable by "proxy" on OPNsense; squid needs it to
		// recover the original destination of an intercepted connection.
		w("cache_effective_group %s", p.Group)
	}
	w("visible_hostname flowsight")
	w("httpd_suppress_version_string on")
	w("shutdown_lifetime 3 seconds")
	w("cache deny all")
	w("cache_mem 32 MB")
	w("maximum_object_size_in_memory 0 KB")
	w("memory_pools off")
	w("via off")
	w("forwarded_for delete")
	w("follow_x_forwarded_for deny all")
	w("request_header_access X-Forwarded-For deny all")
	if len(p.DNSServers) > 0 {
		w("dns_nameservers %s", strings.Join(p.DNSServers, " "))
	}
	w("negative_dns_ttl 1 seconds")
	w("pinger_enable off")
	w("client_db off")
	w("icp_port 0")
	w("htcp_port 0")
	w("snmp_port 0")
	if p.Workers > 1 {
		w("workers %d", p.Workers)
	}
	w("")
	w("# Listeners: loopback only; pf redirects to them. The plain port exists")
	w("# because squid needs one forward-proxy port for its internal URLs.")
	w("http_port 127.0.0.1:%d", p.HTTPPort-1)
	w("http_port 127.0.0.1:%d intercept", p.HTTPPort)
	w("http_port [::1]:%d intercept", p.HTTPPort)
	ssl := ""
	if p.CAPath != "" {
		ssl = fmt.Sprintf(" ssl-bump generate-host-certificates=on dynamic_cert_mem_cache_size=16MB tls-cert=%s "+
			"options=NO_SSLv3,NO_TLSv1,NO_TLSv1_1", p.CAPath)
	} else {
		// Without a CA squid still needs a cert to open an ssl port for peeking;
		// a self-signed placeholder is generated by the module.
		ssl = fmt.Sprintf(" ssl-bump generate-host-certificates=off tls-cert=%s/placeholder.pem", p.Dir)
	}
	w("https_port 127.0.0.1:%d intercept%s", p.HTTPSPort, ssl)
	w("https_port [::1]:%d intercept%s", p.HTTPSPort, ssl)
	if p.V6Listener != "" {
		w("http_port [%s]:%d intercept", p.V6Listener, p.HTTPPort)
		w("https_port [%s]:%d intercept%s", p.V6Listener, p.HTTPSPort, ssl)
	}
	w("")
	if p.CAPath != "" {
		w("sslcrtd_program %s -s %s -M 16MB", p.CertgenBin, p.CertDB)
		w("sslcrtd_children 4 startup=1 idle=1")
	}
	if p.DeepPort > 0 {
		w("")
		w("# Stateful Packet Inspection: each decrypted request and response is handed to")
		w("# flowsightd over ICAP (RFC 3507). FlowSight reads the headers and a")
		w("# short preview of the body, answers 204 No Content, and the exchange")
		w("# continues unmodified. Nothing is proxied through it and no body is kept.")
		w("icap_enable on")
		w("icap_preview_enable on")
		preview := p.DeepPreview
		if preview <= 0 {
			preview = 4096
		}
		w("icap_preview_size %d", preview)
		w("icap_send_client_ip on")
		w("icap_send_client_username off")
		w("icap_service_failure_limit -1")
		w("icap_service fsdeep_req reqmod_precache bypass=on icap://127.0.0.1:%d/reqmod", p.DeepPort)
		w("icap_service fsdeep_resp respmod_precache bypass=on icap://127.0.0.1:%d/respmod", p.DeepPort)
		w("adaptation_service_set fsdeep_set fsdeep_req")
		w("adaptation_service_set fsdeep_resp_set fsdeep_resp")
		// "all" is squid's own ACL and must not be redefined; an empty list
		// simply means "no restriction here".
		scope := ""
		if len(p.DeepClients) > 0 {
			w("acl fs_deep_src src %s", strings.Join(p.DeepClients, " "))
			scope += " fs_deep_src"
		}
		if len(p.DeepNames) > 0 {
			files["deep-names.acl"] = domainList(p.DeepNames)
			w("acl fs_deep_dst ssl::server_name \"%s/deep-names.acl\"", p.Dir)
			scope += " fs_deep_dst"
		}
		if scope == "" {
			scope = " all"
		}
		w("adaptation_access fsdeep_set allow%s", scope)
		w("adaptation_access fsdeep_set deny all")
		w("adaptation_access fsdeep_resp_set allow%s", scope)
		w("adaptation_access fsdeep_resp_set deny all")
	}
	w("tls_outgoing_options options=NO_SSLv3,NO_TLSv1,NO_TLSv1_1 min-version=1.2")
	w("sslproxy_cert_error deny all")
	w("")
	w("# Logging: one line per request with the server name and bump mode, read by flowsightd.")
	w(`logformat flowsight %%ts.%%03tu %%6tr %%>a %%>p %%<a %%<p %%Ss/%%03>Hs %%<st %%>st %%rm "%%ru" %%ssl::>sni %%ssl::bump_mode %%ssl::>negotiated_version "%%ssl::<cert_subject" "%%ssl::<cert_issuer" %%{User-Agent}>h`)
	w("access_log stdio:%s/access.log flowsight", p.LogDir)
	w("cache_log %s/cache.log", p.LogDir)
	w("logfile_rotate 3")
	w("")
	w("acl localnet src %s", strings.Join(nonEmpty(p.LocalNets, "10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 fc00::/7 fe80::/10"), " "))
	w("acl SSL_ports port 443")
	w("acl Safe_ports port 80 443 8080 8443 1025-65535")
	w("acl step1 at_step SslBump1")
	w("acl step2 at_step SslBump2")
	w("acl step3 at_step SslBump3")
	// Address lists live in files, one entry per line. squid reads its
	// configuration a line at a time with a fixed limit of 2048 characters,
	// and an exclusion list that widens to every address a device holds --
	// a laptop cycles through dozens of IPv6 privacy addresses -- passed that
	// on one line and was cut mid-address, at which point squid rejected the
	// whole configuration and interception stopped. A file has no such limit.
	// Every entry is checked first: one malformed address would do the same.
	if excl := addressList(p.Exclusions); excl != "" {
		files["excluded-hosts.acl"] = excl
		w("acl fs_excluded src \"%s/excluded-hosts.acl\"", p.Dir)
	}
	if len(p.ExclDomains) > 0 {
		files["excluded-domains.acl"] = domainList(p.ExclDomains)
		w("acl fs_excluded_sni ssl::server_name \"%s/excluded-domains.acl\"", p.Dir)
		w("acl fs_excluded_host dstdomain -n \"%s/excluded-domains.acl\"", p.Dir)
	}
	w("")
	// Per-policy ACLs.
	// A policy whose members leave nothing valid is dropped here and from
	// every later section, since a rule naming an undefined ACL is as much
	// a rejected configuration as a malformed address.
	kept := p.Policies[:0:0]
	for _, pol := range p.Policies {
		if addressList(pol.Members) != "" {
			kept = append(kept, pol)
		}
	}
	p.Policies = kept
	for _, pol := range p.Policies {
		files["src-"+pol.ID+".acl"] = addressList(pol.Members)
		w("acl fs_src_%s src \"%s/src-%s.acl\"", pol.ID, p.Dir, pol.ID)
		if len(pol.Domains) > 0 {
			files["deny-"+pol.ID+".acl"] = domainList(pol.Domains)
			w("acl fs_deny_sni_%s ssl::server_name \"%s/deny-%s.acl\"", pol.ID, p.Dir, pol.ID)
			w("acl fs_deny_host_%s dstdomain -n \"%s/deny-%s.acl\"", pol.ID, p.Dir, pol.ID)
		}
		if len(pol.Allow) > 0 {
			files["allow-"+pol.ID+".acl"] = domainList(pol.Allow)
			w("acl fs_allow_sni_%s ssl::server_name \"%s/allow-%s.acl\"", pol.ID, p.Dir, pol.ID)
			w("acl fs_allow_host_%s dstdomain -n \"%s/allow-%s.acl\"", pol.ID, p.Dir, pol.ID)
		}
		if pol.Inspect && len(pol.Bypass) > 0 {
			files["bypass-"+pol.ID+".acl"] = domainList(pol.Bypass)
			w("acl fs_bypass_%s ssl::server_name \"%s/bypass-%s.acl\"", pol.ID, p.Dir, pol.ID)
		}
	}
	w("")
	w("# TLS handling. First match per step wins.")
	w("ssl_bump peek step1")
	if files["excluded-hosts.acl"] != "" {
		w("ssl_bump splice fs_excluded")
	}
	if len(p.ExclDomains) > 0 {
		w("ssl_bump splice fs_excluded_sni")
	}
	// Denials at step 2: terminate before any application data.
	for _, pol := range p.Policies {
		if len(pol.Domains) == 0 || pol.Monitor {
			continue
		}
		if len(pol.Allow) > 0 {
			w("ssl_bump splice fs_src_%s fs_allow_sni_%s", pol.ID, pol.ID)
		}
		w("ssl_bump terminate fs_src_%s fs_deny_sni_%s", pol.ID, pol.ID)
	}
	// Inspection: bump for inspected clients, except bypassed names.
	anyInspect := false
	for _, pol := range p.Policies {
		if !pol.Inspect || p.CAPath == "" {
			continue
		}
		anyInspect = true
		if len(pol.Bypass) > 0 {
			w("ssl_bump splice fs_src_%s fs_bypass_%s", pol.ID, pol.ID)
		}
		w("ssl_bump stare fs_src_%s step2", pol.ID)
		w("ssl_bump bump fs_src_%s step3", pol.ID)
	}
	_ = anyInspect
	if p.PeekServerCert {
		w("ssl_bump peek step2")
	}
	w("ssl_bump splice all")
	w("")
	w("# HTTP access. Denied requests get the block page; everything local is allowed.")
	w("http_access deny !Safe_ports")
	w("http_access deny CONNECT !SSL_ports")
	if files["excluded-hosts.acl"] != "" {
		w("http_access allow fs_excluded")
	}
	if len(p.ExclDomains) > 0 {
		w("http_access allow fs_excluded_host")
	}
	blockPage := p.BlockPageURL
	for _, pol := range p.Policies {
		if len(pol.Domains) == 0 || pol.Monitor {
			continue
		}
		if len(pol.Allow) > 0 {
			w("http_access allow fs_src_%s fs_allow_host_%s", pol.ID, pol.ID)
		}
		if blockPage != "" {
			w("deny_info 302:%s?policy=%s&url=%%U fs_deny_host_%s", blockPage, pol.ID, pol.ID)
		}
		w("http_access deny fs_src_%s fs_deny_host_%s", pol.ID, pol.ID)
	}
	w("http_access allow localnet")
	w("http_access allow localhost")
	w("http_access deny all")
	files["squid.conf"] = b.String()
	return b.String(), files
}

func nonEmpty(xs []string, def string) []string {
	if len(xs) == 0 {
		return strings.Fields(def)
	}
	return xs
}

// domainList writes a squid dstdomain/ssl::server_name file: ".example.com"
// matches the name and every subdomain. Squid refuses a list in which one
// entry is a subdomain of another, so entries covered by a parent are
// dropped; the parent already matches them.
// addressList renders client addresses for a src ACL file: one per line,
// only those that parse as an address or a CIDR, deduplicated, sorted so the
// file is stable between renders. Anything else is left out rather than
// handed to squid, which would reject the entire configuration over it.
func addressList(addrs []string) string {
	seen := map[string]bool{}
	var keep []string
	for _, a := range addrs {
		a = strings.TrimSpace(a)
		if a == "" || seen[a] {
			continue
		}
		if _, _, err := net.ParseCIDR(a); err != nil && net.ParseIP(a) == nil {
			continue
		}
		seen[a] = true
		keep = append(keep, a)
	}
	if len(keep) == 0 {
		return ""
	}
	sort.Strings(keep)
	return strings.Join(keep, "\n") + "\n"
}

func domainList(domains []string) string {
	set := map[string]bool{}
	for _, d := range domains {
		d = strings.TrimPrefix(strings.ToLower(d), ".")
		if d != "" {
			set[d] = true
		}
	}
	out := make([]string, 0, len(set))
	for d := range set {
		covered := false
		for rest := d; ; {
			i := strings.Index(rest, ".")
			if i < 0 {
				break
			}
			rest = rest[i+1:]
			if set[rest] {
				covered = true
				break
			}
		}
		if !covered {
			out = append(out, "."+d)
		}
	}
	sort.Strings(out)
	return strings.Join(out, "\n") + "\n"
}

// pfRules renders the redirect rules for the "web" sub-anchor: port 80 and
// 443 from the intercepted networks, to anything that is not local, into the
// proxy listeners. Excluded clients and local destinations are left alone.
func pfRules(lanIfaces []string, nets []string, exclusions []string, httpPort, httpsPort int, localTable string, v6Listener string) string {
	var b strings.Builder
	b.WriteString("# Generated by flowsight web module: transparent interception.\n")
	if len(nets) == 0 {
		return b.String()
	}
	src := "{ " + strings.Join(nets, ", ") + " }"
	if len(lanIfaces) == 0 {
		lanIfaces = []string{""} // any interface
	}
	excl := ""
	if len(exclusions) > 0 {
		fmt.Fprintf(&b, "table <fs_web_excluded> persist { %s }\n", strings.Join(exclusions, ", "))
		excl = "from ! <fs_web_excluded> "
	}
	for _, ifc := range lanIfaces {
		on := ""
		if ifc != "" {
			on = "on " + ifc + " "
		}
		if excl != "" {
			// pf has no "from A and not B" in one rule; use no rdr for the exclusions first.
			// Both families: a device excluded by its IPv4 address is the same
			// device when it speaks IPv6, and exempting only half of it is how
			// a television ends up intercepted on one protocol and not the
			// other. The table carries whichever addresses were resolved.
			fmt.Fprintf(&b, "no rdr %sinet proto tcp from <fs_web_excluded> to any port { 80, 443 }\n", on)
			fmt.Fprintf(&b, "no rdr %sinet6 proto tcp from <fs_web_excluded> to any port { 80, 443 }\n", on)
		}
		fmt.Fprintf(&b, "rdr %sinet proto tcp from %s to ! <%s> port 80 -> 127.0.0.1 port %d\n", on, src, localTable, httpPort)
		fmt.Fprintf(&b, "rdr %sinet proto tcp from %s to ! <%s> port 443 -> 127.0.0.1 port %d\n", on, src, localTable, httpsPort)
		if v6Listener != "" {
			// IPv6 clients hold global addresses, so the local table (which
			// carries the LAN prefixes) is the source, not a literal list.
			fmt.Fprintf(&b, "rdr %sinet6 proto tcp from <%s> to ! <%s> port 80 -> %s port %d\n", on, localTable, localTable, v6Listener, httpPort)
			fmt.Fprintf(&b, "rdr %sinet6 proto tcp from <%s> to ! <%s> port 443 -> %s port %d\n", on, localTable, localTable, v6Listener, httpsPort)
		}
	}
	_ = core.CapWebBlock
	return b.String()
}
